### ISSUE TITLE
API "/api/v1//api/v1/auth/[:action]" is not working, how to use it?

### ISSUE THREAD

**Issue by developerfromjokela** [NatLibFi/NDL-VuFind2#1593]
Hello,

By analyzing the code, I found this API path: `/api/v1/auth/[:action]`, by navigating to it, I get 404 error.
Can someone explain to me how this authentication API works? What's the action?

**Comment by samuli** [comment]
The authentication API can be used to determine whether the login credentials given by a user are correct. The API is only available on agreement.
See here for more information:
https://www.kiwi.fi/pages/viewpage.action?pageId=78382572
https://www.kiwi.fi/display/Finna/Finnan+kirjautumisrajapinta
