### ISSUE TITLE
Where can I get the "arena_2.7.1_catalogue.wsdl" file?

### ISSUE THREAD

**Issue by developerfromjokela** [NatLibFi/NDL-VuFind2#1616]
Hello,

I analyzed the AxiellWebServices.ini, and found these .wsdl filenames referenced there.
These are for finding the SOAP patches right? How/Where can I get one on these files?

**Comment by developerfromjokela** [comment]
My idea is to make my own JSON API for kirkes. So I want to know where did this file come from.
If you're able to tell, where's the base URL for the (SOAP?) API?

**Comment by EreMaijala** [comment]
You would get them from any API you had access to. Unfortunately we cannot provide more support on this since this is not really related to Finna.

**Comment by developerfromjokela** [comment]
Where Can I get the access? Please tell me

**Comment by developerfromjokela** [comment]
I want access to the Kirkes ILS backend API, so where/whom should I contact to?

**Comment by EreMaijala** [comment]
This was already discussed in your previous issue, specifically https://github.com/NatLibFi/NDL-VuFind2/issues/1559#issuecomment-596414300. We cannot provide more assistance on this matter.
