### ISSUE TITLE
I released the app, would you like to advertise it on the Kirkes website?

### ISSUE THREAD

**Issue by developerfromjokela** [NatLibFi/NDL-VuFind2#1627]
Hello,

I've just released my Kirkes App ([https://play.google.com/store/apps/details?id=com.developerfromjokela.kirkes](https://play.google.com/store/apps/details?id=com.developerfromjokela.kirkes)), would you like to put a "advertising" or some sort of banner so users would be aware of this app?

**Comment by EreMaijala** [comment]
No. Kirkes libraries manage all the activities on their site, and third-party apps are generally not advertised. Please refrain from opening any further issues that have nothing to do with the codebase here.

**Comment by developerfromjokela** [comment]
What should I do if kirkes themselves ignores me?

**Comment by EreMaijala** [comment]
Unfortunately we cannot provide assistance with that.

**Comment by developerfromjokela** [comment]
Ok then, @EreMaijala Ask Erkki Tolonen to answer to my emails please
