### ISSUE TITLE
Removing a geo region filter causes the remaining search parameter string to be HTML-escaped

### ISSUE THREAD

**Issue by ttoljamo** [NatLibFi/NDL-VuFind2#2092]
When removing a geographic region filter, the link that is followed opens a URL in which the remaining parameter string is HTML-escaped, which fudges up the search results. 

Example steps to reproduce:  
1. Search for 'poro', time 1950-1960 and a region: 
https://finna.fi/Search/Results?filter%5B%5D=search_daterange_mv%3A%22overlap%7C%5B1950+TO+1960%5D%22&lookfor=poro&filter%5B%5D=%7B%21geofilt+sfield%3Dlocation_geo+pt%3D68.95207844745956%2C26.881348192691807+d%3D55.85383460924077%7D

2. Click to remove the geographic region filter: 
https://finna.fi/Search/Results?filter%5B%5D=search_daterange_mv%3A%22overlap%7C%5B1950+TO+1960%5D%22&amp;lookfor=poro&amp;type=AllFields
-> Bug: All remaining filters are not active, because of the HTML-escaping of & to `&amp;` . 

The issue seems to be in /templates/search/filters.phtml on line 58: 
`<?php if($removeLink): ?><a aria-label="<?=$ariaLabel?>" **href="<?=$this->escapeHtmlAttr($removeLink)?>"**>`...

Best,
Tuomo

**Comment by EreMaijala** [comment]
@ttoljamo Thanks for reporting the issue. Should be fixed now.

**Comment by EreMaijala** [comment]
Alse the filter label will be improved in the next Finna release due 21.9.2021.
