### ISSUE TITLE
Finna.fi main page takes over 10 seconds to load

### ISSUE THREAD

**Issue by nemobis** [NatLibFi/NDL-VuFind2#897]
Is this expected?
https://www.webpagetest.org/result/171214_ZF_22c299a20d6cd54eac6a35fc7e0d5071/

**Comment by EreMaijala** [comment]
No, but that's not the result we generally see. That would happen if the connection is relatively slow. Admittedly we have a relatively large amount of js loaded on the front page and there's definitely room for improvement, but it's currently not one of the main priorities.
